### ISSUE TITLE
Tools in /sbin and /usr/sbin are not reached by users on all systems

### ISSUE THREAD

**Issue by tsjk** [M0Rf30/simonpi#4]
I'm trying out this on Gentoo, and hit some errors because it is assumed that losetup and sysctl in in path for users. For instance,
CUSTOMIMG=$(losetup -l | cut -d " " -f 15 | tail -n +2 | head -n +1) [in simonpiemu/scripts/storage]
won't work, and neither will
IPFORWARD=$(sysctl -n net.ipv4.ip_forward) [in simonpiemu/scripts/network]
because sysctl and losetup are sbin binaries, which are not in path for standard users on my system.

**Comment by M0Rf30** [comment]
could you try now?

**Comment by tsjk** [comment]
I see a lot of changes, although I think most of them weren't really necessary for solving the current problem. I think the sudo -E commands still work, even though sudo is told to keep the environment, because PATH is altered still, at least on my system.
Just changing, for instance, to
IPFORWARD=$(sudo -E sysctl -n net.ipv4.ip_forward)
works here. But I'll try your changes.

**Comment by tsjk** [comment]
Doesn't complain not finding the binaries now. Was a bit confusing that only some of the commit were in the master branch, though. :)

**Comment by M0Rf30** [comment]
Ok now it works, I've replaced sysctl related command with a generic ones like cat and echo (that needs su access to read from /proc path, at least on my distro). The other branch is for a personal project, however, I'll merge meaningful changes on master branch. I'm still considering the use of macvlan instead of tun/tap bridge for network access.
