### ISSUE TITLE
[Fail] No more loopback device available running on ubuntu 18.04

### ISSUE THREAD

**Issue by AlxndrPsclt** [M0Rf30/simonpi#7]
Hello!
I'm using your fantastic project to emulate a set of RPI to work on automatic cluster configuration.

I'm launching several qemu instances using a docker-compose file and your simonpi docker image. I supply the latest raspbian-light image; and run the command
`simonpi rpi-3 -i /root/.simonpi/${SEED_IMAGE_FILENAME} -s 8`

It works great on ubuntu 17.10 (the emulators start as intended); but the same config fails on ubuntu 18.04 with "[Fail] No more loopback device available running"

In simonpiemu/scripts/storage I found this line (l43):
```
if [ ${DEVICE2##*/loop} -gt 5  ]; then
  echo -e "[$FAIL] No more loopback devices available"
  exit 1
fi
```

And indeed, before I even attempt to rurn the emulators, there are at least 16 /dev/loopXX in my ubuntu 18.04 machine (lots of snaps use loopback devices apparently); while there are less than 5 on my ubuntu 17.10 machine.
So my question is why limit the number of loopback devices to 5? Can it be increased? What would be the best way to tackle the issue?

**Comment by AlxndrPsclt** [comment]
I just got it working on Ubuntu 18.04 Server; which had a reasonable amount of /dev/loopXX. But I still don't understand why it should fail on mu ubuntu 18.04 desktop.

**Comment by M0Rf30** [comment]
Fixed here:
https://github.com/M0Rf30/simonpi/commit/99a8f6b62f3a6c0ee4371b976c9c2ad50dd3ce3d
Now it shows only a warning about the used loop devices used. At first the limit of 6 loop devices (it starts to count from 0) because of 3 different instances of simonpi (one for every family) and because of an unmanaged conflict between two instances of the same family using the same sd image.

Thanks for your contribution !

**Comment by AlxndrPsclt** [comment]
Thanks for you attention; works perfectly.
